apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: web
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: kejsiblushi/wordpress_img:v1
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service.db
        - name: WORDPRESS_DB_USER
          value: kejsi
        - name: WORDPRESS_DB_PASSWORD
          value: kejsi2001
        - name: WORDPRESS_DB_NAME
          value: wordpress




